### PR TITLE
CORELOG-179 try to fix http EOF error

### PR DESCRIPTION
**Pull request by andrewmed**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

### CODE REVIEW

**Comment by ssnd** [comment]
could you create and link an issue to this PR that describes the thing you're trying to fix.
and also name the branches according to the guidelines we introduced a few days ago.
it would also be nice to change the default PR description and informative about what we're working on

**Comment by ansakharov** [comment]
Don't leak internal tasks like `CORELOG` please.
Let's create issue and add PR to it.

**Comment by ansakharov** [comment]
- [ ] Update version in top of Makefile

**Comment by andrewmed** [comment]
Closing this one.

Looks like the problem receiver/network related - connection got broken for some reason.

**Pull request closed without merging**
