### PR TITLE
Replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

### PR DESCRIPTION
**Pull request by Juneezee**
# Description

The package `github.com/ghodss/yaml` is no longer actively maintained. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`. It is actively maintained by Kubernetes SIG, and also widely used in K8s projects.

The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, but `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. Changes can be seen here [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), mostly bug fixes.

### CODE REVIEW

**Comment by vadimalekseev** [comment]
Hello! Thanks for your contribution! <3
I sent this PR to my team for testing

**Comment by Juneezee** [comment]
Rebased and resolved conflicts in `go.mod`

**Comment by Juneezee** [comment]
Hi @vadimalekseev . I apologize for the explicit mention, but I wanted to follow up on this pull request I created some time ago. Is this PR ready to be merged now? If there are any specific concerns or questions you have about the changes, I am more than willing to help address them.

Thank you for your time and consideration. I truly appreciate it. :heart:

**Review by vano144 — APPROVED** [review]

**Comment by vadimalekseev** [comment]
Hi @Juneezee!

Sorry for the wait, we tested this release in our production environment and got distracted. Thank you very much for your contribution, we really appreciate it!

:heart: :heart: :heart:

**Pull request merged**
